version: '2'
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    mem_limit: 2G
    cpus: 1
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --syncmode full --http --http.addr 0.0.0.0 --http.vhosts ,* --http.api personal,eth,net,web3,admin,miner --ws --ws.addr 0.0.0.0 --ws.api eth,debug,admin --networkid=666 --txlookuplimit 0 --gcmode archive --allow-insecure-unlock  --snapshot=false --rpc.allow-unprotected-txs'
            #  '--datadir /chain/data --syncmode full --http --http.addr 0.0.0.0 --http.vhosts ,* --http.api eth,debug,admin --ws --ws.addr 0.0.0.0 --ws.api eth,debug,admin --txlookuplimit 0 --gcmode archive
    volumes:
      - ./data/bootstrap:/root/.ethereum
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/localtime:/etc/localtime:ro
    ports:
      - '30303:30303'
      - '30303:30303/udp'
      - '8545:8545'
  # eth:
  #   build: monitored-geth-client
  #   restart: on-failure
  #   container_name: eth
  #   hostname: eth
  #   mem_limit: 2G
  #   cpus: 1
  #   links:
  #     - bootstrap
  #     - netstats
  #   entrypoint: /root/start.sh
  #   volumes:
  #     - ./data/eth:/root/.ethereum
  #     - ./files/genesis.json:/root/files/genesis.json:ro
  #     - ./files/localtime:/etc/localtime:ro
  #   ports:
  #     - '40303:30303'
  #     - '40303:30303/udp'
  #     - '18545:8545'
  #   command: '--datadir=~/.ethereum/devchain --rpcapi "db,personal,eth,net,web3,admin,miner" --rpccorsdomain="*" --networkid=666 --rpc --rpcaddr="0.0.0.0"  --allow-insecure-unlock'
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - ./files/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
